name = "bosonize"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Bosonize"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc3"

[[lean_lib]]
name = "Bosonize"
