import Mathlib

#check ZMod
#check ZMod.val
#check ZMod.natCast_self
#check ZMod.intCast_cast
#check fwdDiff
#check fwdDiff_iter_eq_sum_shift
#check descPochhammer
#check ascPochhammer
#check Polynomial.derivative
#check Polynomial.comp
#check Polynomial.taylor
#check Finset.sum_range_succ_sub_sum
#check Finset.sum_range_sub
#check Finset.sum_range_by_parts
#check IsPrimitiveRoot
#check IsPrimitiveRoot.geom_sum_eq_zero
#check Complex.isPrimitiveRoot_exp
#check Matrix.conjTranspose
#check Matrix.kronecker
#check Matrix.trace_mul_comm
#check Module.End
#check Module.finrank
#check ExteriorAlgebra
#check CliffordAlgebra
#check FreeAlgebra
#check RingQuot
#check Algebra.adjoin
#check StarSubalgebra
#check StarAlgHom
#check AlgEquiv
#check Commute
#check MvPolynomial
#check MvPolynomial.pderiv
#check MvPolynomial.constantCoeff
#check PowerSeries
#check Nat.Partition
#check Finset.powerset
#check Finset.sum_bij
#check Finset.card_powerset